import { describe, expect, it } from "vitest";
import catalogTreeApiSource from "../../api/catalogTree.ts?raw";
import mediaApiSource from "../../api/media.ts?raw";
import advancedPanelSource from "./CatalogAdvancedPanel.tsx?raw";
import aiContextPanelSource from "./CatalogAiContextPanel.tsx?raw";
import editorHeaderSource from "./CatalogEditorHeader.tsx?raw";
import contentPanelSource from "./CatalogNodeContentPanel.tsx?raw";
import nodeStatusPanelSource from "./CatalogNodeStatusPanel.tsx?raw";
import previewWindowSource from "./CatalogPointPreviewWindow.tsx?raw";
import devicePreviewSource from "../device-preview/DevicePreviewFrame.tsx?raw";
import editorSource from "./CatalogTreeEditor.tsx?raw";
import rowSource from "./CatalogTreeRow.tsx?raw";
import treeDataSource from "./catalogTreeData.ts?raw";
import hooksSource from "./catalogTreeHooks.ts?raw";
import treeSource from "./CatalogTreeNodeList.tsx?raw";
import workspaceSource from "./CatalogTreeWorkspacePage.tsx?raw";
import videoPanelSource from "./CatalogVideoPanel.tsx?raw";
import relatedPanelSource from "./CatalogRelatedLinksPanel.tsx?raw";

describe("catalog tree UI contracts", () => {
  it("keeps primary authoring tabs focused and diagnostics secondary", () => {
    expect(editorSource).toContain("directoryCatalogEditorTabKeys");
    expect(editorSource).toContain("pointCatalogEditorTabKeys");
    expect(editorSource).toContain('key: "content"');
    expect(editorSource).toContain('key: "video"');
    expect(editorSource).toContain('key: "related"');
    expect(editorSource).toContain('label: "知识内容"');
    expect(editorSource).toContain('label: "实验视频"');
    expect(editorSource).toContain('label: "相关实验"');
    expect(editorSource).not.toContain('label: "内容"');
    expect(editorSource).not.toContain('label: "视频"');
    expect(editorSource).not.toContain('key: "student-card"');
    expect(editorSource).not.toContain('label: "学生卡片"');
    expect(editorSource).toContain("setDiagnosticsPanel");
    expect(editorSource).toContain("CatalogNodeStatusPanel");
    expect(editorSource).toContain("CatalogAiContextPanel");
    expect(editorSource).toContain("CatalogAdvancedPanel");
    expect(editorSource).not.toContain('key: "publish"');
    expect(editorSource).toContain("previousNodeIdRef");
    expect(editorSource).toContain("selectedNodeChanged");
    expect(editorSource).toContain("if (selectedNodeChanged)");
    expect(editorHeaderSource).toContain("预览学生端");
    expect(editorHeaderSource).toContain("更多");
    expect(editorHeaderSource).toContain("catalogHeaderPrimaryAction");
    expect(editorHeaderSource).toContain("onOpenContentTask");
    expect(editorHeaderSource).toContain("onOpenVideoPicker");
    expect(editorHeaderSource).not.toContain("预览学习卡片");
    expect(devicePreviewSource).toContain("react-device-mockup");
    expect(devicePreviewSource).toContain("iPhone 15 Pro");
    expect(previewWindowSource).toContain("DeviceFrame");
    expect(previewWindowSource).toContain("iframe");
    expect(aiContextPanelSource).toContain("静态兜底证据");
    expect(aiContextPanelSource).toContain("静态证据状态流");
    expect(aiContextPanelSource).toContain("真实 RAG 搜索");
    expect(aiContextPanelSource).toContain("仅教师可见教学备注");
    expect(catalogTreeApiSource).toContain("getCatalogPointAiContext");
    expect(catalogTreeApiSource).toContain("runCatalogPointRagProbe");
    expect(contentPanelSource).toContain('name="point_title" hidden');
    expect(contentPanelSource).not.toContain("多目录共享实验");
    expect(editorHeaderSource).toContain("多目录共享实验");
    expect(editorSource).toContain("contentTaskOpen");
    expect(editorSource).toContain('title="编辑内容"');
    expect(editorSource).toContain("pickerOpen={videoPickerOpen}");
    expect(contentPanelSource).toContain('name="teacher_note"');
    expect(contentPanelSource).toContain('label="教学备注"');
    expect(contentPanelSource).toContain('name="title" hidden');
    expect(contentPanelSource).not.toContain('label="目录标题"');
    expect(contentPanelSource).not.toContain("管理摘要");
    expect(workspaceSource).not.toContain('label="摘要"');
    expect(workspaceSource).not.toContain('name="student_description"');
    expect(catalogTreeApiSource).not.toContain("student_description?:");
    expect(videoPanelSource).toContain("isPointCapable");
    expect([editorSource, contentPanelSource, videoPanelSource, relatedPanelSource, advancedPanelSource].join("\n")).not.toContain(
      "shortcut_target_node_id",
    );
    expect([editorSource, contentPanelSource, videoPanelSource, relatedPanelSource, advancedPanelSource].join("\n")).not.toContain(
      "uploadCatalogPointMedia",
    );
    expect([editorSource, contentPanelSource, videoPanelSource, relatedPanelSource, advancedPanelSource].join("\n")).not.toContain(
      'type="file"',
    );
  });

  it("keeps chapter switching in the heading and resets stale node detail on chapter change", () => {
    expect(workspaceSource).toContain('className="catalog-chapter-switcher"');
    expect(workspaceSource).toContain("if (searchReveal?.nodeId) return;");
    expect(workspaceSource).toContain("setSelectedNodeId(null);");
    expect(workspaceSource).toContain("}, [chapterId, searchReveal?.nodeId]);");
    expect(workspaceSource).toContain('treeScopeKey={chapterId || ""}');
    expect(workspaceSource).not.toContain("chapter-select");
    expect(workspaceSource).toContain("<Dropdown");
    expect(editorSource).toContain("catalog-editor-empty-state");
    expect(editorSource).toContain("<CatalogEditorHeader");
    expect(editorSource).toContain('className="catalog-editor-tabs"');
    expect(editorSource).toContain('className="catalog-editor-direct-panel"');
  });

  it("shows chapter tree summary and counted status filters in the sidebar", () => {
    expect(catalogTreeApiSource).toContain("CatalogChapterTreeSummary");
    expect(catalogTreeApiSource).toContain("CatalogMissingLearningFieldKey");
    expect(catalogTreeApiSource).toContain("point_missing_field_counts");
    expect(catalogTreeApiSource).toContain("/summary");
    expect(workspaceSource).toContain("useCatalogChapterTreeSummary");
    expect(workspaceSource).toContain("CatalogTreeOverview");
    expect(workspaceSource).toContain("CatalogStatusFilterBar");
    expect(workspaceSource).toContain("catalogPrimaryStatusFilterOptions");
    expect(workspaceSource).toContain("catalogMissingFieldFilterOptions");
    expect(workspaceSource).toContain("catalogStatusFilterCount");
    expect(workspaceSource).toContain("搜索标题、实验内容、教学备注、旧实验 ID");
    expect(workspaceSource).toContain('aria-label="章节资源统计"');
    expect(workspaceSource).toContain('aria-label="点位状态筛选"');
    expect(workspaceSource).toContain("待发布");
    expect(workspaceSource).not.toContain("未发布");
  });

  it("keeps teacher search as a floating ES-backed overlay instead of an in-flow tree rewrite", async () => {
    // @ts-expect-error The frontend tsconfig intentionally omits Node types, but Vitest runs this contract in Node.
    const { readFileSync } = await import("node:fs");
    const cwd = (globalThis as unknown as { process: { cwd: () => string } }).process.cwd();
    const styles = readFileSync(`${cwd}/src/features/catalog-tree/catalogTree.css`, "utf8");

    expect(catalogTreeApiSource).toContain("CatalogSearchMeta");
    expect(catalogTreeApiSource).toContain("CatalogSearchResult");
    expect(catalogTreeApiSource).toContain("search_scope");
    expect(catalogTreeApiSource).toContain("scope_totals");
    expect(catalogTreeApiSource).toContain("params.set(\"status_filter\", statusFilter)");
    expect(hooksSource).toContain('queryKey: ["catalog-search", query, chapterId, statusFilter]');
    expect(hooksSource).toContain("searchCatalogNodes(query, chapterId, 80, statusFilter)");
    expect(workspaceSource).toContain("CatalogSearchOverlay");
    expect(workspaceSource).toContain("groupSearchItemsByScope");
    expect(workspaceSource).toContain("current_chapter");
    expect(workspaceSource).toContain("other_chapter");
    expect(workspaceSource).toContain("useCatalogSearch(searchText, chapterId, searchReady, statusFilter)");
    expect(workspaceSource).toContain("handleSearchKeyDown");
    expect(workspaceSource).toContain("document.addEventListener(\"mousedown\"");
    expect(workspaceSource).toContain("selectSearchResult");
    expect(workspaceSource).toContain("setSearchReveal");
    expect(workspaceSource).toContain("revealNodeId={searchReveal?.nodeId}");
    expect(treeSource).toContain("revealNodeId");
    expect(treeSource).toContain("revealPathIds");
    expect(treeSource).toContain("arboristRef.current?.scrollTo(revealNodeId");
    expect(treeSource).toContain("arboristRef.current?.select(revealNodeId");
    expect(styles).toContain(".catalog-tree-searchbox");
    expect(styles).toContain("position: relative");
    expect(styles).toContain(".catalog-search-overlay");
    expect(styles).toContain(".catalog-search-overlay-section-header");
    expect(styles).toContain("position: absolute");
    expect(styles).toContain("max-height");
  });

  it("resets tree open and loaded state at chapter boundaries and workspace resets", () => {
    expect(treeSource).toContain("previousTreeScopeKeyRef");
    expect(treeSource).toContain("previousResetVersionRef");
    expect(treeSource).toContain("loadingDirectoryIdsRef.current.clear()");
    expect(treeSource).toContain("node.chapter_id === treeScopeKey");
    expect(treeSource).toContain("scopeChanged || resetChanged ? [] : previous");
    expect(treeSource).toContain('key={`${treeScopeKey}:${resetVersion}`}');
    expect(workspaceSource).toContain("workspaceResetVersion");
    expect(workspaceSource).toContain("setWorkspaceResetVersion");
    expect(workspaceSource).toContain("resetVersion={workspaceResetVersion}");
    const resetWorkspaceBody = workspaceSource.slice(workspaceSource.indexOf("const resetWorkspace = () => {"), workspaceSource.indexOf("const openCreate"));
    expect(resetWorkspaceBody).not.toContain("setChapterId");
  });

  it("refreshes loaded ancestor branches when selected node detail changes", () => {
    expect(workspaceSource).toContain("selectedBranchDirectoryIds");
    expect(workspaceSource).toContain("selectedDetail.data?.breadcrumbs");
    expect(workspaceSource).toContain("branchRefreshVersion={selectedDetail.dataUpdatedAt}");
    expect(workspaceSource).toContain("branchRefreshDirectoryIds={selectedBranchDirectoryIds}");
    expect(treeSource).toContain("treeDataRef");
    expect(treeSource).toContain("previousBranchRefreshVersionRef");
    expect(treeSource).toContain("refreshLoadedDirectories");
    expect(treeSource).toContain("response.parent");
    expect(treeDataSource).toContain("parentNode?: CatalogNodeCard");
  });

  it("keeps operational/debug fields out of default content panels", () => {
    expect(contentPanelSource).not.toContain("Node ID");
    expect(contentPanelSource).not.toContain("search_preview");
    expect(contentPanelSource).not.toContain("display_order");
    expect(advancedPanelSource).toContain("节点 ID");
    expect(advancedPanelSource).toContain("显示顺序");
    expect(advancedPanelSource).toContain("search_preview");
  });

  it("uses a Chinese natural multiline equation authoring workflow", () => {
    expect(contentPanelSource).toContain('name="reaction_equations_text"');
    expect(contentPanelSource).toContain("buildEquationReviewModel");
    expect(contentPanelSource).toContain("buildReactionEquationRenderRow");
    expect(contentPanelSource).toContain("CatalogReactionEquationRendered");
    expect(contentPanelSource).toContain("catalog-content-form-section");
    expect(contentPanelSource).toContain("catalog-content-section-actions");
    expect(contentPanelSource).toContain("catalog-equation-preview-scroll");
    expect(contentPanelSource).toContain("catalog-student-facing-grid");
    expect(contentPanelSource).toContain("catalog-missing-fields-guide");
    expect(contentPanelSource).toContain("focusMissingField");
    expect(contentPanelSource).toContain("fieldTargetRefs");
    expect(contentPanelSource).toContain("equationEditorRef.current?.focus()");
    expect(contentPanelSource).toContain("onMount={(editorInstance)");
    expect(contentPanelSource).toContain("还缺");
    expect(contentPanelSource).toContain("catalogMissingLearningFieldLabels[fieldKey]");
    expect(contentPanelSource).toContain("RequiredFieldLabel");
    expect(contentPanelSource).toContain("<RequiredFieldLabel>实验原理</RequiredFieldLabel>");
    expect(contentPanelSource).toContain("<RequiredFieldLabel>现象解释</RequiredFieldLabel>");
    expect(contentPanelSource).toContain("<RequiredFieldLabel>安全提示</RequiredFieldLabel>");
    expect(contentPanelSource.indexOf("<Text strong>学生可见内容</Text>")).toBeLessThan(contentPanelSource.indexOf("<RequiredFieldLabel>实验原理</RequiredFieldLabel>"));
    expect(contentPanelSource).toContain("handlePrincipleModeChange");
    expect(contentPanelSource).toContain("Modal.confirm");
    expect(contentPanelSource).toContain("确认切换");
    expect(contentPanelSource).toContain("放弃切换");
    expect(contentPanelSource).toContain("okButtonProps: { danger: true }");
    expect(contentPanelSource).toContain("catalog-equation-natural-candidate");
    expect(contentPanelSource).toContain("catalog-equation-natural-supplemental");
    expect(contentPanelSource).toContain("catalog-equation-natural-empty");
    expect(contentPanelSource).toContain("CatalogEquationCodeEditor");
    expect(contentPanelSource).toContain("catalog-equation-workbench");
    expect(contentPanelSource).toContain("catalog-equation-preview-pane");
    expect(contentPanelSource).toContain("catalog-equation-input-pane");
    expect(contentPanelSource).toContain("catalog-equation-code-editor");
    expect(contentPanelSource).toContain("MonacoEditor");
    expect(contentPanelSource).toContain("CHEM_REACTION_LANGUAGE");
    expect(contentPanelSource).toContain("CHEM_REACTION_THEME");
    expect(contentPanelSource).toContain("configureChemReactionEditor");
    expect(contentPanelSource).toContain("applyCandidate(candidate)");
    expect(contentPanelSource).toContain("catalog-equation-apply-button");
    expect(contentPanelSource).not.toContain("runEquationAssist(equation.row_order)");
    expect(contentPanelSource).toContain('mode: "suggest"');
    expect(contentPanelSource).toContain("previewSeq.current");
    expect(contentPanelSource).toContain("setTimeout");
    expect(contentPanelSource).toContain("500");
    expect(contentPanelSource).toContain("previewCatalogReactionEquations(rows, textValue)");
    expect(contentPanelSource).toContain("assistCatalogReactionEquations");
    expect(contentPanelSource).toContain("catalog-equation-natural-editor");
    expect(contentPanelSource).not.toContain("AI 校对本行");
    expect(contentPanelSource).toContain("AI 校对");
    expect(contentPanelSource).toContain("查看 AI 分析");
    expect(contentPanelSource).not.toContain("系统理解为");
    expect(contentPanelSource).not.toContain("系统校对");
    expect(contentPanelSource).not.toContain("推荐采用");
    expect(contentPanelSource).not.toContain("查看识别详情");
    expect(contentPanelSource).not.toContain("重新检查");
    expect(contentPanelSource).not.toContain("assistAvailable");
    expect(contentPanelSource).not.toContain("applyDrafts");
    expect(contentPanelSource).not.toContain("assistDrafts.length ?");
    expect(contentPanelSource).not.toContain("catalog-equation-card");
    expect(contentPanelSource).not.toContain("catalog-equation-symbol-popover");
    expect(contentPanelSource).not.toContain("catalog-equation-toolbar");
  });

  it("guards point content hydration during local autosave transitions", () => {
    expect(editorSource).toContain("dirtyPointContentNodeIdRef");
    expect(editorSource).toContain("markPointContentLocalChange");
    expect(editorSource).toContain("shouldHydratePointContent");
    expect(editorSource).toContain("if (shouldHydratePointContent)");
    expect(editorSource).toContain("dirtyPointContentNodeIdRef.current = null");
    expect(contentPanelSource).toContain("onLocalContentChange?.()");
    expect(contentPanelSource).toContain("commitPrincipleModeSwitch");
    expect(contentPanelSource).toContain("scheduleAutoSave()");
  });
  it("keeps the video panel as a single active existing-media binding", async () => {
    // @ts-expect-error The frontend tsconfig intentionally omits Node types, but Vitest runs this contract in Node.
    const { readFileSync } = await import("node:fs");
    const cwd = (globalThis as unknown as { process: { cwd: () => string } }).process.cwd();
    const catalogTreeCssSource = readFileSync(`${cwd}/src/features/catalog-tree/catalogTree.css`, "utf8") as string;

    expect(videoPanelSource).toContain("mutations.bindMedia.mutate");
    expect(videoPanelSource).toContain("getMediaAssetFileUrl");
    expect(videoPanelSource).toContain("getMediaAssetThumbnailUrl");
    expect(videoPanelSource).toContain("formatBytes");
    expect(videoPanelSource).toContain("catalog-video-shortcut-card");
    expect(videoPanelSource).toContain("catalog-video-panel-section");
    expect(videoPanelSource).toContain("实验视频");
    expect(videoPanelSource).toContain("视频资源入口");
    expect(videoPanelSource).toContain("CatalogVideoPicker");
    expect(videoPanelSource).toContain("CurrentVideoSlot");
    expect(videoPanelSource).toContain("catalog-video-empty-slot");
    expect(videoPanelSource).toContain("is-blocked");
    expect(videoPanelSource).toContain("先完善学习内容");
    expect(videoPanelSource).toContain("catalog-video-inline-link");
    expect(videoPanelSource).toContain("onOpenContentTask");
    expect(videoPanelSource).toContain("catalog-video-current");
    expect(videoPanelSource).toContain("catalog-video-play-card");
    expect(videoPanelSource).toContain("catalog-video-current-facts");
    expect(videoPanelSource).toContain("catalog-video-current-fact");
    expect(videoPanelSource).toContain("buildCurrentVideoFacts");
    expect(videoPanelSource).toContain("buildCurrentVideoFactRows");
    expect(videoPanelSource).toContain("formatUploadTimestamp");
    expect(videoPanelSource).toContain("formatCurrentVideoBitrate");
    expect(videoPanelSource).toContain("formatCurrentVideoFps");
    expect(videoPanelSource).toContain("playback_file_size_bytes");
    expect(videoPanelSource).toContain("playback_width");
    expect(videoPanelSource).toContain("playback_height");
    expect(videoPanelSource).toContain("playback_bitrate");
    expect(videoPanelSource).toContain("playback_video_codec");
    expect(videoPanelSource).toContain("playback_audio_codec");
    expect(videoPanelSource).toContain("catalog-video-preview-modal");
    expect(videoPanelSource).toContain("catalog-video-preview-player");
    expect(videoPanelSource).toContain("catalog-video-picker-row");
    expect(videoPanelSource).toContain("catalog-video-picker-search");
    expect(videoPanelSource).toContain("更换视频");
    expect(videoPanelSource).toContain("SearchOutlined");
    expect(videoPanelSource).toContain("SwapOutlined");
    expect(videoPanelSource).toContain("PlayCircleFilled");
    expect(videoPanelSource).toContain("<video controls autoPlay");
    expect(videoPanelSource).toContain("asset: MediaAsset");
    expect(videoPanelSource).toContain("pendingMediaId");
    expect(videoPanelSource).toContain("const selecting = pendingMediaId === asset.id");
    expect(videoPanelSource).toContain("loading={selecting}");
    expect(videoPanelSource).toContain('action: "delete"');
    expect(videoPanelSource).not.toContain("<Alert");
    expect(videoPanelSource).not.toContain("<Select");
    expect(videoPanelSource).not.toContain('mode="multiple"');
    expect(videoPanelSource).not.toContain("mediaAssetIds");
    expect(videoPanelSource).not.toContain("setMediaAssetIds");
    expect(videoPanelSource).not.toContain('status: "draft"');
    expect(videoPanelSource).not.toContain('action: "publish"');
    expect(videoPanelSource).not.toContain('action: "unpublish"');
    expect(videoPanelSource).not.toContain("catalog-video-current-meta");
    expect(videoPanelSource).not.toContain('<Text type="secondary" title={binding.original_file_name}>');
    expect(videoPanelSource).not.toContain("请先补全点位学习内容，再绑定实验视频。");
    expect(videoPanelSource).not.toContain("素材就绪");
    expect(videoPanelSource).not.toContain("取消发布");
    expect(editorSource).not.toContain("shortcut_target_node_id");
    expect(editorSource).not.toContain("mediaAssetIds");
    expect(editorSource).not.toContain("setMediaAssetIds");
    expect(catalogTreeApiSource).not.toContain("media/upload");
    expect(catalogTreeApiSource).not.toContain("uploadCatalogPointMedia");
    expect(catalogTreeApiSource).not.toContain('status?: "draft" | "published"');
    expect(catalogTreeApiSource).toContain("playback_file_size_bytes?: number | null");
    expect(catalogTreeApiSource).toContain("playback_width?: number | null");
    expect(catalogTreeApiSource).toContain("playback_height?: number | null");
    expect(catalogTreeApiSource).toContain("playback_duration_seconds?: number | null");
    expect(catalogTreeApiSource).toContain("playback_fps?: number | null");
    expect(catalogTreeApiSource).toContain("playback_bitrate?: number | null");
    expect(catalogTreeApiSource).toContain("playback_video_codec?: string | null");
    expect(catalogTreeApiSource).toContain("playback_audio_codec?: string | null");
    expect(catalogTreeCssSource).toContain(".catalog-video-empty-slot");
    expect(catalogTreeCssSource).toContain(".catalog-video-panel-section");
    expect(catalogTreeCssSource).toContain("--catalog-video-card-target-height");
    expect(catalogTreeCssSource).toContain(".catalog-video-empty-slot.is-blocked");
    expect(catalogTreeCssSource).toContain(".catalog-video-inline-link");
    expect(catalogTreeCssSource).toContain(".catalog-video-current");
    expect(catalogTreeCssSource).toContain(".catalog-video-play-card");
    expect(catalogTreeCssSource).toMatch(/\.catalog-video-empty-slot\s*\{[\s\S]*min-height: var\(--catalog-video-card-target-height\);/);
    expect(catalogTreeCssSource).toMatch(/\.catalog-video-empty-slot\s*\{[\s\S]*justify-content: center;/);
    expect(catalogTreeCssSource).toContain("button.catalog-video-empty-slot:hover");
    expect(catalogTreeCssSource).toMatch(/\.catalog-video-empty-copy strong\s*\{[\s\S]*font-size: 23px;/);
    expect(catalogTreeCssSource).toMatch(/\.catalog-video-current\s*\{[\s\S]*min-height: var\(--catalog-video-card-target-height\);/);
    expect(catalogTreeCssSource).toContain(".catalog-video-current-facts");
    expect(catalogTreeCssSource).toContain(".catalog-video-current-fact");
    expect(catalogTreeCssSource).toMatch(/\.catalog-video-current-side\s*\{[\s\S]*grid-template-rows: auto 1fr auto;/);
    expect(catalogTreeCssSource).toMatch(/\.catalog-video-current-main\s*\{[\s\S]*place-items: start;[\s\S]*text-align: left;/);
    expect(catalogTreeCssSource).toContain(".catalog-video-preview-player");
    expect(catalogTreeCssSource).toContain(".catalog-video-picker-row");
    expect(catalogTreeCssSource).not.toContain(".catalog-media-bind-toolbar");
    expect(catalogTreeCssSource).not.toContain(".catalog-media-row");
    expect(catalogTreeCssSource).not.toContain(".catalog-video-current-meta");
    expect(mediaApiSource).toContain("thumbnail-stream?access_token=");
    expect(mediaApiSource).toContain("return getMediaAssetStreamUrl(assetId, accessToken)");
  });

  it("presents related experiments as an ordered learning list instead of raw link records", async () => {
    // @ts-expect-error The frontend tsconfig intentionally omits Node types, but Vitest runs this contract in Node.
    const { readFileSync } = await import("node:fs");
    const cwd = (globalThis as unknown as { process: { cwd: () => string } }).process.cwd();
    const catalogTreeCssSource = readFileSync(`${cwd}/src/features/catalog-tree/catalogTree.css`, "utf8") as string;

    expect(relatedPanelSource).toContain("同一直接父目录下的其他实验");
    expect(relatedPanelSource).toContain("重置为同目录默认");
    expect(relatedPanelSource).toContain("catalog-related-row");
    expect(relatedPanelSource).toContain("catalog-related-table");
    expect(relatedPanelSource).toContain("catalog-related-table-head");
    expect(relatedPanelSource).toContain("catalog-related-row-index");
    expect(relatedPanelSource).toContain("catalog-related-drag-preview");
    expect(relatedPanelSource).toContain("is-drop-before");
    expect(relatedPanelSource).toContain("is-drop-after");
    expect(relatedPanelSource).toContain("CatalogRelatedExperimentPicker");
    expect(relatedPanelSource).toContain("catalog-related-add-slot");
    expect(relatedPanelSource).toContain("listCatalogRoots");
    expect(relatedPanelSource).toContain("listCatalogChildren");
    expect(relatedPanelSource).toContain("buildCatalogRelatedLinksPayload({ links: normalized })");
    expect(relatedPanelSource).toContain("setLinks([], true)");
    expect(relatedPanelSource).toContain("MoreHorizontal");
    expect(relatedPanelSource).toContain("catalog-related-panel-section");
    expect(relatedPanelSource).not.toContain("<span>来源</span>");
    expect(relatedPanelSource).not.toContain("<span>操作</span>");
    expect(relatedPanelSource).not.toContain("catalog-related-source-tag");
    expect(relatedPanelSource).not.toContain("catalog-related-card");
    expect(relatedPanelSource).not.toContain("catalog-related-drag-handle");
    expect(relatedPanelSource).not.toContain("catalog-related-search");
    expect(relatedPanelSource).not.toContain("catalog-related-candidate");
    expect(relatedPanelSource).not.toContain("relatedQuery");
    expect(relatedPanelSource).not.toContain("relatedSearch");
    expect(relatedPanelSource).not.toContain('htmlType="submit"');
    expect(editorSource).not.toContain("relatedQuery");
    expect(relatedPanelSource).not.toContain("HolderOutlined");
    expect(relatedPanelSource).not.toContain("ArrowUpOutlined");
    expect(relatedPanelSource).not.toContain("ArrowDownOutlined");
    expect(relatedPanelSource).not.toContain("拖动调整顺序");
    expect(relatedPanelSource).not.toContain("显示名称");
    expect(relatedPanelSource).not.toContain("短名称");
    expect(relatedPanelSource).not.toContain('name={[field.name, "label"]}');
    expect(relatedPanelSource).not.toContain("目标点位 Node ID");
    expect(relatedPanelSource).not.toContain("添加相关链接");
    expect(relatedPanelSource).not.toContain('label="关系"');
    expect(catalogTreeCssSource).toContain(".catalog-related-row");
    expect(catalogTreeCssSource).toContain(".catalog-related-table");
    expect(catalogTreeCssSource).toContain(".catalog-related-table-head");
    expect(catalogTreeCssSource).toContain(".catalog-related-panel-section");
    expect(catalogTreeCssSource).toContain(".catalog-related-row:nth-child(odd)");
    expect(catalogTreeCssSource).toContain(".catalog-related-row-index");
    expect(catalogTreeCssSource).not.toContain(".catalog-related-source-tag");
    expect(catalogTreeCssSource).toContain(".catalog-related-row.is-drop-before::before");
    expect(catalogTreeCssSource).toContain(".catalog-related-row.is-drop-after::after");
    expect(catalogTreeCssSource).toContain(".catalog-related-drag-preview");
    expect(catalogTreeCssSource).toContain(".catalog-related-add-slot");
    expect(catalogTreeCssSource).toContain(".catalog-related-picker-tree");
    expect(catalogTreeCssSource).not.toContain(".catalog-related-card");
    expect(catalogTreeCssSource).not.toContain(".catalog-related-search");
    expect(catalogTreeCssSource).not.toContain(".catalog-related-candidate");
  });

  it("uses Arborist movement with invalid point-drop feedback instead of Ant Design Tree behavior", () => {
    expect(treeSource).toContain('from "react-arborist"');
    expect(treeSource).toContain("onMove={handleMove}");
    expect(treeSource).toContain("disableDrop=");
    expect(treeSource).toContain("resolveCatalogArboristMove");
    expect(treeSource).toContain("resolveCatalogDropDisabled");
    expect(treeSource).toContain("applyCatalogTreeMoveOptimistically");
    expect(treeSource).toContain("renderDragPreview={DragPreviewRenderer}");
    expect(treeSource).toContain("onRefreshRoots");
    expect(workspaceSource).toContain("mutateAsync");
    expect(treeDataSource).toContain("targetParent?.kind === \"point\"");
    expect(treeDataSource).toContain("applyCatalogTreeMoveOptimistically");
    expect(treeSource).toContain("onReorder");
    expect(treeSource).toContain("onMove");
    expect(treeSource).not.toMatch(/import\s*\{[^}]*\bTree\b[^}]*\}\s*from\s*"antd"/);
    expect(treeSource).not.toContain("titleRender");
    expect(treeSource).not.toContain("onDrop");
    expect(treeSource).not.toContain("switcherIcon");
  });

  it("uses the sidebar tree skin with experiment-specific point icons", () => {
    expect(rowSource).toContain("ChevronRight");
    expect(rowSource).toContain("ChevronDown");
    expect(rowSource).toContain("FolderOpen");
    expect(rowSource).toContain("FlaskConical");
    expect(rowSource).toContain("catalog-sidebar-switcher-spacer");
    expect(rowSource).toContain("catalog-sidebar-trailing");
    expect(rowSource).toContain("catalog-sidebar-status-dot");
    expect(rowSource).toContain("catalog-sidebar-point-status");
    expect(rowSource).toContain("CatalogStatusCompositeWarningIcon");
    expect(rowSource).toContain("CatalogArboristModernDragPreview");
    expect(rowSource).toContain("offset || mouse");
    expect(rowSource).toContain("node.isDragging");
    expect(rowSource).toContain("setTimeout");
    expect(rowSource).toContain("500");
    expect(rowSource).toContain("descendant_point_count");
    expect(rowSource).not.toContain("{catalogNode.status}");
    expect(rowSource).not.toContain("catalog-tree-status-tag");
    expect(rowSource).not.toContain("视频 ${catalogNode.published_media_count}");
    expect(rowSource).not.toContain("FileTextOutlined");
    expect(rowSource).not.toContain("HolderOutlined");
    expect(rowSource).not.toContain("catalog-tree-drag-handle");
    expect([treeSource, rowSource].join("\n")).not.toContain("ArrowUpOutlined");
    expect([treeSource, rowSource].join("\n")).not.toContain("ArrowDownOutlined");
  });

  it("keeps the sidebar tree clipped horizontally while preserving vertical scrolling", async () => {
    // @ts-expect-error The frontend tsconfig intentionally omits Node types, but Vitest runs this contract in Node.
    const { readFileSync } = await import("node:fs");
    const cwd = (globalThis as unknown as { process: { cwd: () => string } }).process.cwd();
    const catalogTreeCssSource = readFileSync(`${cwd}/src/features/catalog-tree/catalogTree.css`, "utf8") as string;

    expect(catalogTreeCssSource).toContain("overflow-x: hidden !important");
    expect(catalogTreeCssSource).toContain("overflow-y: auto !important");
    expect(catalogTreeCssSource).toMatch(/\.catalog-arborist-tree > div,[\s\S]*\.catalog-arborist-tree > div > div\s*\{[\s\S]*min-width: 0 !important;/);
    expect(catalogTreeCssSource).toMatch(/\.catalog-arborist-tree > div > div\s*\{[\s\S]*overflow: hidden;/);
    expect(catalogTreeCssSource).toContain("--catalog-sidebar-trailing-width: 130px");
    expect(catalogTreeCssSource).toContain("grid-template-columns: 20px 24px minmax(0, 1fr) var(--catalog-sidebar-trailing-width)");
    expect(catalogTreeCssSource).toMatch(/\.catalog-sidebar-item\s*\{[\s\S]*box-sizing: border-box;[\s\S]*width: 100%;[\s\S]*max-width: 100%;[\s\S]*overflow: hidden;/);
    expect(catalogTreeCssSource).toMatch(/\.catalog-sidebar-row\s*\{[\s\S]*box-sizing: border-box;[\s\S]*width: 100%;[\s\S]*max-width: 100%;[\s\S]*min-width: 0;/);
    expect(catalogTreeCssSource).toMatch(/\.catalog-sidebar-copy\s*\{[\s\S]*box-sizing: border-box;[\s\S]*min-width: 0;[\s\S]*overflow: hidden;/);
    expect(catalogTreeCssSource).toMatch(/\.catalog-sidebar-trailing\s*\{[\s\S]*box-sizing: border-box;[\s\S]*width: var\(--catalog-sidebar-trailing-width\);/);
    expect(catalogTreeCssSource).toContain(".catalog-sidebar-status-dot.is-error");
    expect(catalogTreeCssSource).toContain(".catalog-sidebar-point-status.is-error");
    expect(catalogTreeCssSource).toContain(".catalog-editor-title-status.is-error");
    expect(catalogTreeCssSource).toContain(".catalog-composite-warning-icon");
    expect(rowSource).toContain('boxSizing: "border-box"');
  });

  it("keeps sidebar guide lines row-clipped while preserving L-shaped branch states", () => {
    expect(treeSource).toContain("rowHeight={38}");
    expect(treeSource).toContain("Math.max(520, treeBoxSize.height || 620)");
    expect(rowSource).toContain("node.childIndex === 0");
    expect(rowSource).toContain("is-first");
    expect(rowSource).toContain("is-only");
    expect(rowSource).toContain("is-terminal");
    expect(rowSource).toContain("is-continuing");
    expect(rowSource).not.toContain("--catalog-tree-half-row");
  });

  it("keeps add wording chapter-oriented instead of root-node oriented", () => {
    expect(workspaceSource).not.toContain("PlusOutlined");
    expect(workspaceSource).not.toContain("<Space.Compact>");
    expect(workspaceSource).toContain("catalog-tree-filterbar");
    expect(treeSource).toContain("添加到本章");
    expect(treeSource).toContain("新建目录");
    expect(treeSource).toContain("新建点位");
    expect(treeSource).not.toContain("新建根目录");
    expect(treeSource).not.toContain("新建根点位");
    expect(workspaceSource).toContain("引用已有实验");
    expect(workspaceSource).toContain("引用到当前目录");
    expect(workspaceSource).toContain("canonical_point_id");
  });

  it("distinguishes fixed-source and fixed-target copy actions instead of exposing Node ID copying", () => {
    expect(rowSource).toContain('"copy-node"');
    expect(rowSource).toContain("复制当前目录");
    expect(rowSource).toContain("引用当前实验");
    expect(rowSource).toContain("从已有目录复制到此目录");
    expect(rowSource).toContain("从已有实验引用到此目录");
    expect(rowSource).not.toContain("复制节点");
    expect(rowSource).not.toContain('"copy-id"');
    expect(rowSource).not.toContain("复制 Node ID");
    expect(treeSource).toContain("onCopyNode");
    expect(treeSource).toContain("onCopyInto");
    expect(treeSource).toContain("从已有目录复制到本章");
    expect(treeSource).toContain("从已有实验引用到本章");
    expect(workspaceSource).toContain("copyIntent");
    expect(workspaceSource).toContain('"fixed-source"');
    expect(workspaceSource).toContain('"fixed-target"');
    expect(workspaceSource).toContain('targetParentId: node.node_kind === "point" ? null : node.parent_id || null');
    expect(workspaceSource).toContain("copySourceSearchText");
    expect(workspaceSource).toContain("selectCopySource");
    expect(workspaceSource).toContain("来源");
    expect(workspaceSource).toContain("目标位置");
    expect(workspaceSource).toContain("copySemanticsNote");
    expect(workspaceSource).toContain("引用实验会在目标目录新增一个点位入口");
    expect(workspaceSource).toContain("复制目录会创建新的目录结构");
    expect(workspaceSource).toContain("请引用已有点位，不要新建节点");
    expect(workspaceSource).toContain("CatalogCopyDestinationTree");
    expect(workspaceSource).toContain('return title || "未命名节点";');
    expect(workspaceSource).toContain('label="节点名称"');
    expect(workspaceSource).not.toContain("副本名称");
    expect(workspaceSource).not.toContain("复制点位");
    expect(workspaceSource).not.toContain("复制当前实验");
    expect(workspaceSource).not.toContain("从已有实验复制");
    expect(catalogTreeApiSource).toContain("copyCatalogNode");
    expect(catalogTreeApiSource).toContain("/copy");
  });

  it("renders editor status labels in Chinese instead of backend enum text", () => {
    expect(editorHeaderSource).toContain("catalogStatusLabel(node.status)");
    expect(editorHeaderSource).not.toContain("{node.status}</Tag>");
    expect(editorHeaderSource).toContain("pointContentSummary(detail)");
    expect(contentPanelSource).not.toContain("{detail.point_content?.content_status ||");
  });

  it("keeps autosave labels scoped to backend persistence and explains delayed ES/RAG sync", () => {
    expect(contentPanelSource).toContain("contentAutoSaveDisplayLabel");
    expect(contentPanelSource).toContain("正在保存");
    expect(contentPanelSource).toContain("已保存");
    expect(contentPanelSource).toContain("保存失败");
    expect(contentPanelSource).toContain("目录信息");
    expect(contentPanelSource).toContain("目录负责学生端导航与分类，不承载点位知识或视频绑定。编辑内容会自动保存；停止编辑 30 秒或连续编辑 3 分钟进行资源同步。");
    expect(contentPanelSource).toContain("知识内容");
    expect(contentPanelSource).toContain("维护教师备注、实验原理、现象解释和安全提示。 编辑内容会自动保存；停止编辑 30 秒或连续编辑 3 分钟进行资源同步。");
    expect(contentPanelSource).not.toContain("基础信息");
    expect(contentPanelSource).not.toContain("保存点位内容");
    expect(contentPanelSource).not.toContain("保存目录内容");
  });

  it("gates directory-only editor queries and tabs", () => {
    expect(editorSource).toContain('["content"]');
    expect(editorSource).toContain('["content", "video", "related"]');
    expect(editorSource).toContain("useCatalogMediaAssets(pointCapable)");
    expect(editorSource).not.toContain("useCatalogSearch");
    expect(editorSource).not.toContain("relatedQuery");
  });

  it("groups node status panel diagnostics without the legacy publish-check panel", () => {
    expect(editorSource).toContain("CatalogNodeStatusPanel");
    expect(editorSource).not.toContain("CatalogPublishChecksPanel");
    expect(nodeStatusPanelSource).toContain("核心完整性");
    expect(nodeStatusPanelSource).toContain("学生可见性");
    expect(nodeStatusPanelSource).toContain("同步诊断");
    expect(nodeStatusPanelSource).toContain("刷新 ES");
    expect(nodeStatusPanelSource).toContain("刷新 RAG");
    expect(nodeStatusPanelSource).toContain("重试失败任务");
  });
});
