ARG ELASTICSEARCH_VERSION=8.11.3
ARG ELASTICSEARCH_IMAGE_DIGEST=sha256:2892d2363c3c12c5ed54c64faf89e3a19d633d8dd0d190d0bffe03035ff099b3
FROM docker.elastic.co/elasticsearch/elasticsearch:${ELASTICSEARCH_VERSION}@${ELASTICSEARCH_IMAGE_DIGEST}

ARG ANALYSIS_IK_VERSION=8.11.3
RUN bin/elasticsearch-plugin install --batch "https://get.infini.cloud/elasticsearch/analysis-ik/${ANALYSIS_IK_VERSION}"

COPY data/seed/search/es_ik/analysis-ik/ /usr/share/elasticsearch/config/analysis-ik/
COPY data/seed/search/es_ik/analysis/ /usr/share/elasticsearch/config/analysis/
