FROM node:22-alpine@sha256:ab07539e0988b63558ff621f5fbe1077054c39d9809112974fb79993949d41cd AS build

ARG APP_DIR
WORKDIR /app

COPY ${APP_DIR}/package.json ${APP_DIR}/package-lock.json ./
COPY ${APP_DIR}/scripts ./scripts
RUN npm ci

COPY ${APP_DIR}/ ./
COPY apps/shared /shared
RUN npm run build

FROM nginx:1.27-alpine@sha256:65645c7bb6a0661892a8b03b89d0743208a18dd2f3f17a54ef4b76fb8e2f2a10

ENV BACKEND_UPSTREAM=http://backend:8000
ENV FRAME_ANCESTORS="'self'"

COPY server/nginx/frontend.conf.template /etc/nginx/templates/default.conf.template
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
