import { periodicElements } from "../../periodic";

export type PeriodicElementSearchMeta = (typeof periodicElements)[number];

const englishElementNames: Record<string, string> = {
  H: "hydrogen",
  He: "helium",
  Li: "lithium",
  Be: "beryllium",
  B: "boron",
  C: "carbon",
  N: "nitrogen",
  O: "oxygen",
  F: "fluorine",
  Ne: "neon",
  Na: "sodium",
  Mg: "magnesium",
  Al: "aluminium aluminum",
  Si: "silicon",
  P: "phosphorus",
  S: "sulfur sulphur",
  Cl: "chlorine",
  Ar: "argon",
  K: "potassium",
  Ca: "calcium",
  Sc: "scandium",
  Ti: "titanium",
  V: "vanadium",
  Cr: "chromium",
  Mn: "manganese",
  Fe: "iron ferrum",
  Co: "cobalt",
  Ni: "nickel",
  Cu: "copper cuprum",
  Zn: "zinc",
  Ga: "gallium",
  Ge: "germanium",
  As: "arsenic",
  Se: "selenium",
  Br: "bromine",
  Kr: "krypton",
  Rb: "rubidium",
  Sr: "strontium",
  Y: "yttrium",
  Zr: "zirconium",
  Nb: "niobium",
  Mo: "molybdenum",
  Tc: "technetium",
  Ru: "ruthenium",
  Rh: "rhodium",
  Pd: "palladium",
  Ag: "silver argentum",
  Cd: "cadmium",
  In: "indium",
  Sn: "tin stannum",
  Sb: "antimony stibium",
  Te: "tellurium",
  I: "iodine",
  Xe: "xenon",
  Cs: "caesium cesium",
  Ba: "barium",
  La: "lanthanum",
  Ce: "cerium",
  Pr: "praseodymium",
  Nd: "neodymium",
  Pm: "promethium",
  Sm: "samarium",
  Eu: "europium",
  Gd: "gadolinium",
  Tb: "terbium",
  Dy: "dysprosium",
  Ho: "holmium",
  Er: "erbium",
  Tm: "thulium",
  Yb: "ytterbium",
  Lu: "lutetium",
  Hf: "hafnium",
  Ta: "tantalum",
  W: "tungsten wolfram",
  Re: "rhenium",
  Os: "osmium",
  Ir: "iridium",
  Pt: "platinum",
  Au: "gold aurum",
  Hg: "mercury hydrargyrum",
  Tl: "thallium",
  Pb: "lead plumbum",
  Bi: "bismuth",
  Po: "polonium",
  At: "astatine",
  Rn: "radon",
  Fr: "francium",
  Ra: "radium",
  Ac: "actinium",
  Th: "thorium",
  Pa: "protactinium",
  U: "uranium",
  Np: "neptunium",
  Pu: "plutonium",
  Am: "americium",
  Cm: "curium",
  Bk: "berkelium",
  Cf: "californium",
  Es: "einsteinium",
  Fm: "fermium",
  Md: "mendelevium",
  No: "nobelium",
  Lr: "lawrencium",
  Rf: "rutherfordium",
  Db: "dubnium",
  Sg: "seaborgium",
  Bh: "bohrium",
  Hs: "hassium",
  Mt: "meitnerium",
  Ds: "darmstadtium",
  Rg: "roentgenium",
  Cn: "copernicium",
  Nh: "nihonium",
  Fl: "flerovium",
  Mc: "moscovium",
  Lv: "livermorium",
  Ts: "tennessine",
  Og: "oganesson",
};

const chineseElementAliases: Record<string, string[]> = {
  H: ["氢", "氫"],
  He: ["氦"],
  Li: ["锂", "鋰"],
  Be: ["铍", "鈹"],
  B: ["硼"],
  C: ["碳"],
  N: ["氮"],
  O: ["氧"],
  F: ["氟"],
  Ne: ["氖"],
  Na: ["钠", "鈉"],
  Mg: ["镁", "鎂"],
  Al: ["铝", "鋁"],
  Si: ["硅", "矽"],
  P: ["磷"],
  S: ["硫"],
  Cl: ["氯"],
  Ar: ["氩", "氬"],
  K: ["钾", "鉀"],
  Ca: ["钙", "鈣"],
  Sc: ["钪", "鈧"],
  Ti: ["钛", "鈦"],
  V: ["钒", "釩"],
  Cr: ["铬", "鉻"],
  Mn: ["锰", "錳"],
  Fe: ["铁", "鐵"],
  Co: ["钴", "鈷"],
  Ni: ["镍", "鎳"],
  Cu: ["铜", "銅"],
  Zn: ["锌", "鋅"],
  Ga: ["镓", "鎵"],
  Ge: ["锗", "鍺"],
  As: ["砷"],
  Se: ["硒"],
  Br: ["溴"],
  Kr: ["氪"],
  Rb: ["铷", "銣"],
  Sr: ["锶", "鍶"],
  Y: ["钇", "釔"],
  Zr: ["锆", "鋯"],
  Nb: ["铌", "鈮"],
  Mo: ["钼", "鉬"],
  Tc: ["锝", "鍀"],
  Ru: ["钌", "釕"],
  Rh: ["铑", "銠"],
  Pd: ["钯", "鈀"],
  Ag: ["银", "銀"],
  Cd: ["镉", "鎘"],
  In: ["铟", "銦"],
  Sn: ["锡", "錫"],
  Sb: ["锑", "銻"],
  Te: ["碲"],
  I: ["碘"],
  Xe: ["氙"],
  Cs: ["铯", "銫"],
  Ba: ["钡", "鋇"],
  La: ["镧", "鑭"],
  Ce: ["铈", "鈰"],
  Pr: ["镨", "鐠"],
  Nd: ["钕", "釹"],
  Pm: ["钷", "鉕"],
  Sm: ["钐", "釤"],
  Eu: ["铕", "銪"],
  Gd: ["钆", "釓"],
  Tb: ["铽", "鋱"],
  Dy: ["镝", "鏑"],
  Ho: ["钬", "鈥"],
  Er: ["铒", "鉺"],
  Tm: ["铥", "銩"],
  Yb: ["镱", "鐿"],
  Lu: ["镥", "鑥"],
  Hf: ["铪", "鉿"],
  Ta: ["钽", "鉭"],
  W: ["钨", "鎢"],
  Re: ["铼", "錸"],
  Os: ["锇", "鋨"],
  Ir: ["铱", "銥"],
  Pt: ["铂", "鉑"],
  Au: ["金"],
  Hg: ["汞", "水银", "水銀"],
  Tl: ["铊", "鉈"],
  Pb: ["铅", "鉛"],
  Bi: ["铋", "鉍"],
  Po: ["钋", "釙"],
  At: ["砹"],
  Rn: ["氡"],
  Fr: ["钫", "鈁"],
  Ra: ["镭", "鐳"],
  Ac: ["锕", "錒"],
  Th: ["钍", "釷"],
  Pa: ["镤", "鏷"],
  U: ["铀", "鈾"],
  Np: ["镎", "錼"],
  Pu: ["钚", "鈈"],
  Am: ["镅", "鎇"],
  Cm: ["锔", "鋦"],
  Bk: ["锫", "鉳"],
  Cf: ["锎", "鉲"],
  Es: ["锿", "鑀"],
  Fm: ["镄", "鐨"],
  Md: ["钔", "鍆"],
  No: ["锘", "鍩"],
  Lr: ["铹", "鐒"],
  Nh: ["鉨", "nihonium"],
  Fl: ["鈇", "flerovium"],
  Mc: ["镆", "鏌", "moscovium"],
  Lv: ["鉝", "livermorium"],
  Ts: ["tennessine"],
  Og: ["oganesson"],
};

export function normalizePeriodicElementQuery(value: string): string {
  return value
    .normalize("NFKC")
    .trim()
    .toLowerCase()
    .replace(/[\s\-_/.,，。·・'’"“”()（）\[\]【】]/g, "");
}

function aliasesForElement(element: PeriodicElementSearchMeta): string[] {
  const englishAliases = (englishElementNames[element.symbol] || "").split(/\s+/).filter(Boolean);
  return [element.symbol, String(element.atomicNumber), element.name, ...englishAliases, ...(chineseElementAliases[element.symbol] || [])]
    .map(normalizePeriodicElementQuery)
    .filter(Boolean);
}

function elementMatchRank(element: PeriodicElementSearchMeta, query: string): number {
  const aliases = aliasesForElement(element);
  if (aliases.some((alias) => alias === query)) return 0;
  if (aliases.some((alias) => alias.startsWith(query))) return 1;
  if (aliases.some((alias) => alias.includes(query))) return 2;
  return Number.POSITIVE_INFINITY;
}

export function searchPeriodicElements(query: string): PeriodicElementSearchMeta[] {
  const normalizedQuery = normalizePeriodicElementQuery(query);
  if (!normalizedQuery) return [];
  return periodicElements
    .map((element) => ({ element, rank: elementMatchRank(element, normalizedQuery) }))
    .filter((item) => Number.isFinite(item.rank))
    .sort((a, b) => a.rank - b.rank || a.element.atomicNumber - b.element.atomicNumber)
    .map((item) => item.element);
}

export function exactPeriodicElementMatches(query: string): PeriodicElementSearchMeta[] {
  const normalizedQuery = normalizePeriodicElementQuery(query);
  if (!normalizedQuery) return [];
  return periodicElements.filter((element) => aliasesForElement(element).some((alias) => alias === normalizedQuery));
}
